export const STATES = [
  "Punjab",
  "Haryana",
  "Himachal Pradesh",
  "Uttarakhand",
  "Uttar Pradesh",
  "Rajasthan",
  "Gujarat",
  "Maharashtra",
  "Karnataka",
  "Tamil Nadu",
  "Telangana",
  "Andhra Pradesh",
  "West Bengal",
  "Odisha",
  "Jharkhand",
  "Bihar",
  "Madhya Pradesh",
];
